kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sandbox-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8085
        protocol: TCP
      - containerPort: 443
        hostPort: 8445
        protocol: TCP
